# -*- coding: utf-8 -*-
"""Build2EXE.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kWbiGuC72Qujr1svnDOqcaDN4sHfNLQW
"""

# Magnetar Agent – EXE Builder with GitHub Actions
# Copyright © 2026 Magnetar. All rights reserved.

!pip install -qU langchain langchain-openai pydantic langgraph gradio requests==2.32.4

import os
import re
import time
import json
import shutil
import zipfile
import subprocess
import requests
import threading
from datetime import datetime
from typing import TypedDict, List, Optional

import gradio as gr
from google.colab import userdata

from langgraph.graph import StateGraph, START, END
from langchain_openai import ChatOpenAI
from langchain_core.tools import tool
from langchain_core.messages import BaseMessage, SystemMessage, ToolMessage

# =========================================================
# CONFIG
# =========================================================
MODEL_NAME = "gpt-4.1-mini"
TEMPERATURE = 0

WORKSPACE_DIR = "/content/workspace"
RUNS_DIR = os.path.join(WORKSPACE_DIR, "runs")

MAX_REACT_STEPS = 18
MAX_PATCH_ROUNDS = 4

COPYRIGHT_LINE = "© 2026 Magnetar. All rights reserved."

GITHUB_USER = "shubham-61291"
GITHUB_REPO = "agentic-exe-builder_1"
WORKFLOW_FILE = "build-exe.yml"

thread_local = threading.local()

# =========================================================
# SECRETS
# =========================================================
def get_secret(name: str) -> str:
    v = userdata.get(name)
    if not v:
        raise RuntimeError(f"Missing secret: {name}. Add in Colab: Runtime → Secrets → {name}")
    return v

os.environ["OPENAI_API_KEY"] = get_secret("OPENAI_API_KEY")
GITHUB_TOKEN = get_secret("GITHUB_TOKEN")

# =========================================================
# UTILS
# =========================================================
def now_run_id() -> str:
    return datetime.utcnow().strftime("%Y%m%d_%H%M%S")

def ensure_dir(p: str):
    os.makedirs(p, exist_ok=True)

def safe_relpath(path: str) -> str:
    path = path.replace("\\", "/").strip()
    path = path.lstrip("/")
    path = path.replace("..", "")
    path = re.sub(r"^[.]+", "", path)
    return path

def write_text(path: str, content: str):
    ensure_dir(os.path.dirname(path))
    if isinstance(content, str):
        content = content.replace("\x00", "")
    with open(path, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)

def read_text(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()

def run_cmd(cmd: str, cwd: str, timeout: int = 900):
    p = subprocess.run(
        cmd,
        cwd=cwd,
        shell=True,
        capture_output=True,
        text=True,
        timeout=timeout
    )
    return p.returncode, p.stdout, p.stderr

# =========================================================
# RUN DIR
# =========================================================
def init_run_dir() -> str:
    ensure_dir(WORKSPACE_DIR)
    ensure_dir(RUNS_DIR)

    run_id = now_run_id()
    run_dir = os.path.join(RUNS_DIR, run_id)

    ensure_dir(run_dir)
    ensure_dir(os.path.join(run_dir, "src"))
    ensure_dir(os.path.join(run_dir, "logs"))
    ensure_dir(os.path.join(run_dir, "release"))
    return run_dir

# =========================================================
# TOOLS
# =========================================================
@tool
def write_file(filename: str, content: str) -> str:
    """Write content to a file in the workspace. Use this to create or overwrite any text file."""
    try:
        run_dir = thread_local.current_run_dir
        filename = safe_relpath(filename)
        full_path = os.path.join(run_dir, filename)
        write_text(full_path, content)
        return f"OK: wrote {filename}"
    except Exception as e:
        return f"ERROR(write_file): {str(e)}"

@tool
def read_file(filename: str) -> str:
    """Read and return the contents of a file in the workspace."""
    try:
        run_dir = thread_local.current_run_dir
        filename = safe_relpath(filename)
        full_path = os.path.join(run_dir, filename)
        return read_text(full_path)
    except Exception as e:
        return f"ERROR(read_file): {str(e)}"

TOOLS_LIST = [write_file, read_file]

# =========================================================
# STATE
# =========================================================
class AgentState(TypedDict):
    requirements: str
    run_dir: str
    status: str
    logs: List[str]
    messages: List[BaseMessage]
    patch_round: int
    exe_path: Optional[str]

def log_line(state: AgentState, msg: str):
    ts = datetime.now().strftime("%H:%M:%S")
    state["logs"].append(f"[{ts}] {msg}")

# =========================================================
# MODEL
# =========================================================
llm = ChatOpenAI(model=MODEL_NAME, temperature=TEMPERATURE).bind_tools(TOOLS_LIST)

# =========================================================
# GITHUB HELPERS
# =========================================================
API = "https://api.github.com"

def gh_headers():
    return {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application/vnd.github+json"
    }

def gh_get(url):
    r = requests.get(url, headers=gh_headers())
    if r.status_code >= 300:
        raise RuntimeError(f"GitHub GET failed: {r.status_code} {r.text[:400]}")
    return r.json()

def push_to_unique_branch(run_dir: str, run_id: str) -> str:
    branch_name = f"build-{run_id}"

    local_repo = os.path.join(run_dir, "repo")
    if os.path.exists(local_repo):
        shutil.rmtree(local_repo)

    repo_url = f"https://{GITHUB_TOKEN}@github.com/{GITHUB_USER}/{GITHUB_REPO}.git"
    rc, out, err = run_cmd(f"git clone {repo_url} {local_repo}", cwd=run_dir, timeout=300)
    if rc != 0:
        raise RuntimeError("git clone failed:\n" + (err or out)[-1000:])

    rc, out, err = run_cmd(f"git checkout -b {branch_name}", cwd=local_repo, timeout=120)
    if rc != 0:
        raise RuntimeError("git checkout -b failed:\n" + (err or out)[-1000:])

    ensure_dir(os.path.join(local_repo, "src"))
    shutil.copy(os.path.join(run_dir, "src", "main.py"), os.path.join(local_repo, "src", "main.py"))
    shutil.copy(os.path.join(run_dir, "requirements.txt"), os.path.join(local_repo, "requirements.txt"))

    run_cmd("git config user.email 'bot@colab.local'", cwd=local_repo)
    run_cmd("git config user.name 'Colab Bot'", cwd=local_repo)

    run_cmd("git add .", cwd=local_repo)
    run_cmd(f"git commit -m \"Auto build {run_id}\"", cwd=local_repo)

    rc, out, err = run_cmd(f"git push origin {branch_name}", cwd=local_repo, timeout=300)
    if rc != 0 and "nothing to commit" not in (out + err).lower():
        raise RuntimeError("git push failed:\n" + (err or out)[-1000:])

    return branch_name

def trigger_workflow(branch_name: str):
    url = f"{API}/repos/{GITHUB_USER}/{GITHUB_REPO}/actions/workflows/{WORKFLOW_FILE}/dispatches"
    payload = {"ref": branch_name}
    r = requests.post(url, headers=gh_headers(), json=payload)
    if r.status_code != 204:
        raise RuntimeError(f"Workflow dispatch failed: {r.status_code} {r.text[:400]}")

def get_latest_run_id(branch_name: str = None):
    url = f"{API}/repos/{GITHUB_USER}/{GITHUB_REPO}/actions/runs?per_page=5"
    if branch_name:
        url += f"&branch={branch_name}"

    data = gh_get(url)
    runs = data.get("workflow_runs", [])
    if not runs:
        return None
    return runs[0]["id"]

def wait_for_run_completion(run_id: int, timeout_sec=900):
    start = time.time()
    while time.time() - start < timeout_sec:
        url = f"{API}/repos/{GITHUB_USER}/{GITHUB_REPO}/actions/runs/{run_id}"
        data = gh_get(url)
        status = data.get("status")
        conclusion = data.get("conclusion")
        if status == "completed":
            return conclusion
        time.sleep(5)
    raise RuntimeError("Timed out waiting for GitHub Actions run to complete.")

def download_artifact_zip(run_id: int, run_dir: str) -> str:
    url = f"{API}/repos/{GITHUB_USER}/{GITHUB_REPO}/actions/runs/{run_id}/artifacts"
    data = gh_get(url)
    artifacts = data.get("artifacts", [])
    if not artifacts:
        raise RuntimeError("No artifacts found in run.")

    target = None
    for a in artifacts:
        if a.get("name") == "windows-exe":
            target = a
            break

    if not target:
        raise RuntimeError(f"Artifact 'windows-exe' not found. Found: {[a.get('name') for a in artifacts]}")

    download_url = target["archive_download_url"]
    r = requests.get(download_url, headers=gh_headers(), stream=True)
    if r.status_code >= 300:
        raise RuntimeError(f"Artifact download failed: {r.status_code} {r.text[:200]}")

    out_zip = os.path.join(run_dir, "release", "windows-exe.zip")
    ensure_dir(os.path.dirname(out_zip))

    with open(out_zip, "wb") as f:
        for chunk in r.iter_content(chunk_size=8192):
            if chunk:
                f.write(chunk)

    return out_zip

def extract_exe(artifact_zip: str, run_dir: str) -> str:
    out_dir = os.path.join(run_dir, "release")
    ensure_dir(out_dir)

    with zipfile.ZipFile(artifact_zip, "r") as z:
        z.extractall(out_dir)

    found = None
    for root, _, files in os.walk(out_dir):
        for fn in files:
            if fn.lower() == "app.exe":
                found = os.path.join(root, fn)
                break
        if found:
            break

    if not found or not os.path.exists(found):
        raise RuntimeError("app.exe not found inside artifact zip.")

    final_exe = os.path.join(run_dir, "release", "app.exe")
    if os.path.abspath(found) == os.path.abspath(final_exe):
        return final_exe

    shutil.copy(found, final_exe)
    return final_exe

# =========================================================
# NODES
# =========================================================
def scaffold_node(state: AgentState):
    log_line(state, "Workspace initialized.")
    state["status"] = "Workspace ready."
    return state

def react_codegen_node(state: AgentState):
    log_line(state, "ReAct agent: generating code + requirements via tool actions...")

    system_prompt = f"""
You are a ReAct-style coding agent.

GOAL:
Generate a complete Windows Python application in:
- src/main.py
- requirements.txt

MANDATORY RULES:
1) Use ONLY these tools: write_file, read_file.
2) You MUST write src/main.py and requirements.txt using write_file.
3) requirements.txt must include ONLY required packages.
4) The app MUST run with: python src/main.py
5) The app MUST support: --help (print usage and exit).
6) The application MUST show this exact line somewhere visible to the user:
{COPYRIGHT_LINE}
7) NEVER include null bytes. Output must be plain UTF-8 text.
8) After you finish writing files, STOP calling tools.

User requirement:
{state["requirements"]}
""".strip()

    state["messages"] = [SystemMessage(content=system_prompt)]

    for step in range(1, MAX_REACT_STEPS + 1):
        log_line(state, f"ReAct step {step}: thinking + acting...")

        resp = llm.invoke(state["messages"])
        state["messages"].append(resp)

        tool_calls = getattr(resp, "tool_calls", None)
        if not tool_calls:
            log_line(state, "ReAct: no more tool calls → codegen complete.")
            state["status"] = "Files written."
            return state

        for tc in tool_calls:
            tool_name = tc["name"]
            tool_args = tc["args"]

            log_line(state, f"Tool call: {tool_name}({list(tool_args.keys())})")

            tool_fn = next((t for t in TOOLS_LIST if t.name == tool_name), None)
            if tool_fn is None:
                out = f"ERROR: unknown tool {tool_name}"
            else:
                out = tool_fn.invoke(tool_args)

            state["messages"].append(ToolMessage(tool_call_id=tc["id"], content=str(out)))
            log_line(state, f"Tool result: {str(out)[:120]}")

    log_line(state, "ReAct: max steps reached (continuing).")
    state["status"] = "Files written."
    return state

def sanity_node(state: AgentState):
    log_line(state, "Sanity check: python -m py_compile src/main.py")
    rc, out, err = run_cmd("python -m py_compile src/main.py", cwd=state["run_dir"], timeout=120)

    if rc != 0:
        log_line(state, "Auto-repair in progress... (This is normal and automatic)")
        log_line(state, (err or out)[:1200])
        state["status"] = "Sanity failed."
    else:
        state["status"] = "Sanity passed."
    return state

def patch_node(state: AgentState):
    if state["status"] == "Sanity passed.":
        return state

    if state["patch_round"] >= MAX_PATCH_ROUNDS:
        state["status"] = "FAILED: max patch rounds reached."
        log_line(state, state["status"])
        return state

    state["patch_round"] += 1
    log_line(state, f"Patch round {state['patch_round']}...")

    logs_tail = "\n".join(state["logs"][-140:])

    system_prompt = f"""
You are a ReAct-style debugger.

Sanity check failed. Logs:
{logs_tail}

You MUST:
- Fix src/main.py (and requirements.txt if needed)
- Use write_file only
- Make minimal changes
- Ensure python -m py_compile src/main.py will pass
- Ensure app still meets requirement and includes the copyright {COPYRIGHT_LINE}.

Stop calling tools when done.
""".strip()

    state["messages"] = [SystemMessage(content=system_prompt)]

    for step in range(1, MAX_REACT_STEPS + 1):
        log_line(state, f"Patch ReAct step {step}...")

        resp = llm.invoke(state["messages"])
        state["messages"].append(resp)

        tool_calls = getattr(resp, "tool_calls", None)
        if not tool_calls:
            log_line(state, "Patch ReAct: no more tool calls → patch applied.")
            state["status"] = "Patch applied."
            return state

        for tc in tool_calls:
            tool_name = tc["name"]
            tool_args = tc["args"]

            log_line(state, f"Tool call: {tool_name}({list(tool_args.keys())})")

            tool_fn = next((t for t in TOOLS_LIST if t.name == tool_name), None)
            if tool_fn is None:
                out = f"ERROR: unknown tool {tool_name}"
            else:
                out = tool_fn.invoke(tool_args)

            state["messages"].append(ToolMessage(tool_call_id=tc["id"], content=str(out)))
            log_line(state, f"Tool result: {str(out)[:120]}")

    state["status"] = "Patch applied."
    return state

def github_build_node(state: AgentState):
    run_id = os.path.basename(state["run_dir"])
    log_line(state, f"Pushing code to unique branch: build-{run_id}...")

    branch_name = push_to_unique_branch(state["run_dir"], run_id)

    log_line(state, f"Triggering GitHub Actions Windows build on branch={branch_name}...")
    trigger_workflow(branch_name)

    time.sleep(4)

    run_id_gh = get_latest_run_id(branch_name=branch_name)
    if not run_id_gh:
        raise RuntimeError("No workflow run found after dispatch.")

    log_line(state, f"GitHub Actions run_id={run_id_gh} started. Waiting...")
    conclusion = wait_for_run_completion(run_id_gh, timeout_sec=900)
    log_line(state, f"GitHub Actions completed: {conclusion}")

    if conclusion != "success":
        state["status"] = f"EXE build failed on GitHub: {conclusion}"
        return state

    log_line(state, "Downloading artifact zip...")
    artifact_zip = download_artifact_zip(run_id_gh, state["run_dir"])

    log_line(state, "Extracting app.exe...")
    exe_path = extract_exe(artifact_zip, state["run_dir"])

    state["exe_path"] = exe_path
    state["status"] = "BUILD SUCCESSFUL"
    return state

# =========================================================
# GRAPH
# =========================================================
workflow = StateGraph(AgentState)

workflow.add_node("scaffold", scaffold_node)
workflow.add_node("react_codegen", react_codegen_node)
workflow.add_node("sanity", sanity_node)
workflow.add_node("patch", patch_node)
workflow.add_node("github_build", github_build_node)

workflow.add_edge(START, "scaffold")
workflow.add_edge("scaffold", "react_codegen")
workflow.add_edge("react_codegen", "sanity")

def after_sanity(state: AgentState) -> str:
    if state["status"] == "Sanity passed.":
        return "github_build"
    else:
        return "patch"

workflow.add_conditional_edges("sanity", after_sanity, {"github_build": "github_build", "patch": "patch"})
workflow.add_edge("patch", "sanity")
workflow.add_edge("github_build", END)

agent = workflow.compile()

# =========================================================
# GRADIO
# =========================================================
def run_agent(requirements: str):
    run_dir = init_run_dir()
    thread_local.current_run_dir = run_dir

    state: AgentState = {
        "requirements": requirements,
        "run_dir": run_dir,
        "status": "Initializing...",
        "logs": [],
        "messages": [],
        "patch_round": 0,
        "exe_path": None
    }

    yield "Initializing...", "", None

    try:
        for event in agent.stream(state):
            for node_name, node_state in event.items():
                state = node_state
                status = state.get("status", "Running...")
                logs = "\n".join(state.get("logs", [])[-600:])
                exe_path = state.get("exe_path")
                if exe_path and not os.path.exists(exe_path):
                    exe_path = None
                file_out = gr.File(value=exe_path) if exe_path else None
                yield f"{status} (node={node_name})", logs, file_out

        final_exe = state.get("exe_path")
        if final_exe and os.path.exists(final_exe):
            yield "BUILD SUCCESSFUL — app.exe is ready for download", "\n".join(state.get("logs", [])[-600:]), gr.File(value=final_exe)

    except Exception as e:
        logs = "\n".join(state.get("logs", [])[-600:])
        yield f"ERROR: {str(e)}", logs, None

with gr.Blocks(title="Magnetar – Prompt. Build. Launch.") as demo:
    gr.Markdown(f"# Magnetar – Prompt. Build. Launch. — {COPYRIGHT_LINE}")
    gr.Markdown("Describe your Windows application in plain English. The AI agent will generate the code, validate it, and deliver a real `.exe` file.")

    req_input = gr.Textbox(
        label="App Requirements",
        lines=6,
        placeholder="e.g., 'Build a scientific calculator with sin/cos and memory functions' or 'Create a To-Do list app with save and load'"
    )
    run_btn = gr.Button("BUILD WINDOWS EXE", variant="primary")

    with gr.Row():
        status_box = gr.Textbox(label="Backend Agent Status", interactive=False)
        exe_download = gr.File(label="Download app.exe")

    log_display = gr.Code(label="Live Agent Logs", interactive=False)

    run_btn.click(run_agent, inputs=[req_input], outputs=[status_box, log_display, exe_download])

demo.queue()
demo.launch(share=True)